### ISSUE TITLE
wejs.org slowness

### ISSUE THREAD

**Issue by fuzzthink** [wejs/we#110]
Hi,
  wejs.org seems really slow. Wondering if it's built with wejs or not.

**Comment by albertosouza** [comment]
It seems normal here but I will look and profile

**Comment by fuzzthink** [comment]
Loading from CA, US.  Each page takes ~5-10 secs to load. Retried today from different location/IP, same.

**Comment by albertosouza** [comment]
May be external files, glyphicon or iframes (like btn) i will change this.

**Comment by albertosouza** [comment]
Hi @fuzzthink  you can test now?

I changed the Nginx settings for this site to use http cache for public assets files. May speed up this project with local or regional caching

**Comment by fuzzthink** [comment]
Oh, much better!  Response is ~1 sec or less now.

**Comment by albertosouza** [comment]
ok, thanks for this report
