### ISSUE TITLE
Change express.js core router to hapi.js?

### ISSUE THREAD

**Issue by albertosouza** [wejs/we#118]

**Comment by mnzt** [comment]
Is there any reason? Personally I believe it should stay as Express, due to express becoming recognised and supported by the Node.js foundation.

**Comment by albertosouza** [comment]
@mnzt i agree with you.
Its only a proposal added here for discussion send by @thebergamo in one Node.js slark group but the priority is to finish We.js 1.0 and the base Blog, Conference portal and Social network distributions (full featured projects generated by yeoman generator)

and thanks for your comment

**Comment by albertosouza** [comment]
And now I need to maintain stability of wejs/we-core

**Comment by albertosouza** [comment]
Express and its middlewares is working as expected then i will close this issue
