### ISSUE TITLE
Setting database in local.js

### ISSUE THREAD

**Issue by gohackfelipe** [wejs/we#128]
It is not possible to configure the database with the entry below

mysql://username:password@host/database

For instance, if i am not using default port 3306 for mysql, how can we set this? I did this according with documentation...

 ` dev: {
      host:'localhost:13306',
      dialect: 'mysql',
      database: 'wejs',
      username: 'root',
      password: '12345'
    }`

Thanks all!

**Comment by albertosouza** [comment]
Hi @gohackfelipe ,  thanks for your feedback.

I willl update the docs but this configs accepts all options avaible in: http://sequelize.readthedocs.org/en/latest/api/sequelize/#class-sequelize

With Port settings use:

```js 
  database: {
    dev: {
      port: '13306',
      dialect: 'mysql',
      database: 'wejs',
      username: 'root',
      password: '12345'      
    }
 }
```

URI settings is unstable for now but i will add it for heroku host

**Comment by gohackfelipe** [comment]
That is it! Sorry, i really can use following this way....
The documents are updated .. I have not seen it....

http://sequelize.readthedocs.org/en/latest/api/sequelize/#class-sequelize

Thanks for your quick response!

**Comment by albertosouza** [comment]
Reports are always welcome, now the documentation are better

**Comment by albertosouza** [comment]
I think the question is solved and the documentation is updated then lets close this issue.

fell free to reopen if find any problem related to this issue.
