### ISSUE TITLE
Example of applications online

### ISSUE THREAD

**Issue by gohackfelipe** [wejs/we#129]
Hey ya!

Do you have any online examples of we.js running?

Thanks!

**Comment by albertosouza** [comment]
I only have sites online with we.js v1.0 but the we.js site have one working messenger room in homepage, documenation from github (git clone) and plugins and themes pages with filter and from githubAPI

https://wejs.org/ -> https://github.com/wejs/site
https://groups.wejs.org/ -> https://github.com/wejs-examples/we-project-groups (desenv)
https://events.wejs.org/event -> https://github.com/wejs-examples/events.wejs.org (prod ready)
http://albertosouza.net/ 

For 100% SPA i was working in one messenger with ember.js but i need more help for end:

https://github.com/wejs-examples/we-client-emberjs-messenger (client)
https://github.com/wejs-examples/we-project-messenger (server)

**Comment by albertosouza** [comment]
All resources routes have one JSON version of the page, try to add `Accept= Application/json` in header or `?resopnseType=json` in url.

Example: http://albertosouza.net/article?responseType=json

And you may create onthers plugins for change responseType to others formats like the RSS http://albertosouza.net/article?responseType=rss

**Comment by albertosouza** [comment]
Hi @gohackfelipe if want to make one simple API check the we.js v1.4.x+ API project in generator-wejs
I think the question is solved then i will close this issue. thanks

**Comment by gohackfelipe** [comment]
Hey @albertosouza 
Thanks guy!
