### ISSUE TITLE
 we run have error 

### ISSUE THREAD

**Issue by hoaibac** [wejs/we#167]
The file configuration.json was created
Error on bootstrap:
...w\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };

Can't create table `news`.`userprivacities` (errno: 150 "Foreign key constraint is incorrectly formed")
                           ^

**Comment by albertosouza** [comment]
Hi @hoaibac ,
Is the first time that i see this error in one we.js project ... lets find the problem.

What is your database?
You have changed the type of user model id?
You have run the `yo wejs:app` comand?

**Comment by hoaibac** [comment]
@albertosouza It's done. My Database is exist. Thank  for support.

**Comment by albertosouza** [comment]
Ok, thanks for you feedback.
